version: "3.3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    command: sh -c "gunicorn teloprogramo.wsgi:application --bind 0.0.0.0:9000 --reload"
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app/backend
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - backend.env
  run_code:
    build: ./backend/run_code
    container_name: run_code
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock