<<<<<<< Updated upstream
# Generated by Django 5.0 on 2024-01-18 11:46
=======
# Generated by Django 4.2.4 on 2024-01-12 22:01
>>>>>>> Stashed changes

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsuarioPersonalizado",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id_usuario",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("nombre", models.CharField(max_length=50, null=True)),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, db_column="ultimo_acceso", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("monedas", models.SmallIntegerField(default=0)),
            ],
            options={
                "db_table": "usuarios",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("ESTUDIANTE", "Estudiante"),
                            ("PROFESOR", "Profesor"),
                            ("ADMIN", "Administrador"),
                            ("AYUDANTE", "Ayudante"),
                            ("COORDINADOR", "Coordinador"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
<<<<<<< Updated upstream
            name="Docente",
=======
            name="Estudiante",
>>>>>>> Stashed changes
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asignatura", models.CharField(max_length=150)),
<<<<<<< Updated upstream
=======
                ("paralelo", models.CharField(max_length=10)),
                ("semestre", models.CharField(max_length=10)),
>>>>>>> Stashed changes
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
<<<<<<< Updated upstream
            name="Estudiante",
=======
            name="Docente",
>>>>>>> Stashed changes
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asignatura", models.CharField(max_length=150)),
<<<<<<< Updated upstream
                ("paralelo", models.CharField(max_length=10)),
                ("semestre", models.CharField(max_length=10)),
=======
>>>>>>> Stashed changes
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usuariopersonalizado",
            name="roles",
            field=models.ManyToManyField(to="usuario.rol"),
        ),
    ]
