# Generated by Django 4.2.4 on 2023-10-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='id_usuario',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
