# Generated by Django 4.2.4 on 2023-10-29 18:58

from django.db import migrations

def create_roles(apps, schema_editor):
    Rol = apps.get_model('usuario', 'Rol')
    
    roles_data = [
        ("ESTUDIANTE", "Estudiante"),
        ("PROFESOR", "Profesor"),
        ("ADMIN", "Administrador"),
        ("AYUDANTE", "Ayudante"),
        ("COORDINADOR", "Coordinador"),
    ]

    for nombre, descripcion in roles_data:
        Rol.objects.get_or_create(nombre=nombre, descripcion=descripcion)


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0002_alter_usuariopersonalizado_id_usuario"),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
