# Generated by Django 4.2.4 on 2024-01-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0003_auto_20231029_1858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rol",
            name="nombre",
            field=models.CharField(
                choices=[
                    ("ESTUDIANTE", "Estudiante"),
                    ("PROFESOR", "Profesor"),
                    ("ADMIN", "Administrador"),
                    ("AYUDANTE", "Ayudante"),
                    ("COORDINADOR", "Coordinador"),
                ],
                max_length=50,
            ),
        ),
    ]
