# Generated by Django 4.2.4 on 2024-01-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="institution",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
