# Generated by Django 4.2.4 on 2024-03-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subject",
        ),
        migrations.AddField(
            model_name="customuser",
            name="subject",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
