# Generated by Django 4.2.4 on 2024-02-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0001_initial"),
        ("user", "0002_customuser_institution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="section",
        ),
        migrations.AddField(
            model_name="customuser",
            name="campus",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                db_column="institution",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="subject",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.JSONField(),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="user",
        ),
    ]
