# Generated by Django 4.2.4 on 2024-03-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_student_subject_remove_teacher_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="picture",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="user_photos/"
            ),
        ),
    ]
