# Generated by Django 4.2.4 on 2024-02-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institution", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("contents", models.TextField()),
                (
                    "institution",
                    models.ForeignKey(
                        db_column="institution_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="institution.institution",
                    ),
                ),
            ],
            options={
                "db_table": "subject",
            },
        ),
    ]
