# Generated by Django 4.2.4 on 2024-02-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("institution_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("website", models.URLField(max_length=100)),
                ("description", models.TextField()),
                ("campus", models.JSONField()),
            ],
            options={
                "db_table": "institution",
            },
        ),
    ]
