# Generated by Django 5.0 on 2024-01-18 11:46

import django.db.models.deletion
import ejercicio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleIntento",
            fields=[
                ("id_intento", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField()),
                ("nota", models.PositiveSmallIntegerField()),
                ("resuelto", models.BooleanField()),
                ("retroalimentacion", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "detalle_intentos",
            },
        ),
        migrations.CreateModel(
            name="DetalleRetroalimentacion",
            fields=[
                (
                    "id_retroalimentacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "conversacion_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ejercicio.models.conversacion_directory_path,
                    ),
                ),
                (
                    "codigo_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ejercicio.models.codigo_directory_path,
                    ),
                ),
                (
                    "resultado_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ejercicio.models.resultado_casos_de_uso_directory_path,
                    ),
                ),
                ("estrellas", models.PositiveSmallIntegerField(default=0)),
                (
                    "id_intento",
                    models.ForeignKey(
                        db_column="id_intento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ejercicio.detalleintento",
                    ),
                ),
            ],
            options={
                "db_table": "detalle_retroalimentacion",
            },
        ),
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                ("id_ejercicio", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "enunciado_file",
                    models.FileField(
                        upload_to=ejercicio.models.enunciado_directory_path
                    ),
                ),
                (
                    "casos_de_uso_file",
                    models.FileField(
                        upload_to=ejercicio.models.casos_de_uso_directory_path
                    ),
                ),
                (
                    "ejemplo_file",
                    models.FileField(upload_to=ejercicio.models.ejemplo_directory_path),
                ),
                (
                    "salida_file",
                    models.FileField(upload_to=ejercicio.models.salida_directory_path),
                ),
                ("resumen", models.TextField()),
                ("descripcion", models.TextField()),
                ("dificultad", models.CharField(max_length=100)),
                ("contenidos", models.CharField(max_length=100)),
                ("puntaje", models.PositiveSmallIntegerField()),
                ("lenguaje", models.CharField(max_length=20)),
                ("asignatura", models.CharField(max_length=30)),
                ("titulo", models.CharField(max_length=100)),
                ("restricciones", models.TextField()),
                ("head", models.CharField(max_length=100)),
                ("tail", models.CharField(max_length=100)),
                ("binary", models.BooleanField(default=False)),
                ("contraints", models.TextField()),
                ("formato_entrada", models.TextField()),
                ("formato_salida", models.TextField()),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ejercicios",
            },
        ),
        migrations.CreateModel(
            name="IntentoEjercicio",
            fields=[
                (
                    "id_intento_general",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("intentos", models.PositiveSmallIntegerField(default=0)),
                ("nota", models.PositiveSmallIntegerField(default=0)),
                ("tiempo", models.CharField(max_length=20)),
                ("resuelto", models.BooleanField(default=False)),
                (
                    "id_ejercicio",
                    models.ForeignKey(
                        db_column="id_ejercicio",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ejercicio.ejercicio",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intentos",
            },
        ),
        migrations.AddField(
            model_name="detalleintento",
            name="id_intento_general",
            field=models.ForeignKey(
                db_column="id_intento_general",
                on_delete=django.db.models.deletion.CASCADE,
                to="ejercicio.intentoejercicio",
            ),
        ),
    ]
