# Generated by Django 4.2.4 on 2023-12-16 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intentoejercicio",
            name="id_ejercicio",
            field=models.ForeignKey(
                db_column="id_ejercicio",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intentos_ejercicio",
                to="ejercicio.ejercicio",
            ),
        ),
    ]
