# Generated by Django 4.2.4 on 2023-12-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicio", "0002_alter_intentoejercicio_id_ejercicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleretroalimentacion",
            name="id_intento",
            field=models.ForeignKey(
                db_column="id_intento",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_intentos",
                to="ejercicio.detalleintento",
            ),
        ),
    ]
