# Generated by Django 4.2.4 on 2023-12-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicio", "0004_alter_detalleretroalimentacion_id_intento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleintento",
            name="id_intento_general",
            field=models.ForeignKey(
                db_column="id_intento_general",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_intentos",
                to="ejercicio.intentoejercicio",
            ),
        ),
    ]
