# Generated by Django 4.2.4 on 2024-01-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicio", "0005_alter_detalleintento_id_intento_general"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleintento",
            name="id_intento_general",
            field=models.ForeignKey(
                db_column="id_intento_general",
                on_delete=django.db.models.deletion.CASCADE,
                to="ejercicio.intentoejercicio",
            ),
        ),
        migrations.AlterField(
            model_name="intentoejercicio",
            name="id_ejercicio",
            field=models.ForeignKey(
                db_column="id_ejercicio",
                on_delete=django.db.models.deletion.CASCADE,
                to="ejercicio.ejercicio",
            ),
        ),
    ]
